#- name: Install node exporter
# apt:
#   name: prometheus-node-exporter
#   state: present
#
#- name: Ensure node exporter running
# service:
#   name: prometheus-node-exporter
#   state: started
# enabled: yes
#----------------------------------------------------------------------------------------------------------------
- name: Ensure node exporter running
  service:
    name: node_exporter
    state: started
    enabled: true

